# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb22dd71cff8a203a2d7b1a7a2764e21cad6da377f71d54f4881b58efa4dc7e40b4359bcd0b62a0552579b58f3eda9cf4f0eec8ebd967e61a1de49082d4d5fdf

test:
  secret_key_base: b14b01703cc7b0cfb4d457c53307ca1dd36adc486781e105bd9818ab119b4d0d5e55c2f5bcebbbee29401432411cb22ff6b03c5390615c6b71d66a28a0894104

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
